In [1]:
import numpy as np

# 1. Matrix and Vector Operations

# Create a 3x3 matrix A and a 3x1 vector B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([1, 2, 3])

# - Perform matrix-vector multiplication A * B
A_x_B = np.dot(A, B)
print("Matrix-Vector multiplication (A * B):")
print(A_x_B)

# - Calculate the trace of matrix A (sum of diagonal elements)
trace_A = np.trace(A)
print(f"Trace of matrix A: {trace_A}")

# - Find the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of matrix A:", eigenvalues)
print("Eigenvectors of matrix A:")
print(eigenvectors)

Matrix-Vector multiplication (A * B):
[14 32 50]
Trace of matrix A: 15
Eigenvalues of matrix A: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors of matrix A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [2]:
# 2. Replace the last row of matrix A with [10, 11, 12]
A[2] = [10, 11, 12]
print("\nUpdated matrix A:")
print(A)

# - Compute the determinant of the updated matrix A
det_A = np.linalg.det(A)
print(f"Determinant of updated matrix A: {det_A}")

# - Check if the matrix is singular or non-singular
if det_A != 0:
    print("The updated matrix A is non-singular.")
else:
    print("The updated matrix A is singular.")


Updated matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
Determinant of updated matrix A: 2.86437540353291e-15
The updated matrix A is non-singular.


In [3]:
# 3. Invertibility of Matrices

# - Verify the invertibility of the updated matrix A
if det_A != 0:
    inverse_A = np.linalg.inv(A)
    print("\nInverse of updated matrix A:")
    print(inverse_A)
else:
    print("\nMatrix A is singular, cannot compute inverse.")

# - Solve the system of linear equations A * X = B
if det_A != 0:
    X = np.linalg.solve(A, B)
    print("\nSolution to the system of linear equations (A * X = B):")
    print(X)
else:
    print("\nCannot solve the system of equations, as matrix A is singular.")


Inverse of updated matrix A:
[[-2.09469750e+15  3.14204625e+15 -1.04734875e+15]
 [ 4.18939500e+15 -6.28409250e+15  2.09469750e+15]
 [-2.09469750e+15  3.14204625e+15 -1.04734875e+15]]

Solution to the system of linear equations (A * X = B):
[ 1.04734875e+15 -2.09469750e+15  1.04734875e+15]


In [4]:
# 4. Practical Matrix Operations

# Create a 4x4 matrix C with random integers between 1 and 20
C = np.random.randint(1, 21, size=(4, 4))
print("\nMatrix C:")
print(C)

# - Compute the rank of C
rank_C = np.linalg.matrix_rank(C)
print(f"Rank of matrix C: {rank_C}")

# - Extract the submatrix consisting of the first 2 rows and last 2 columns of C
submatrix_C = C[:2, -2:]
print("Submatrix consisting of the first 2 rows and last 2 columns of C:")
print(submatrix_C)

# - Calculate the Frobenius norm of C
frobenius_norm_C = np.linalg.norm(C, 'fro')
print(f"Frobenius norm of matrix C: {frobenius_norm_C}")

# - Perform matrix multiplication between A and C (3x3) 
C_trimmed = C[:3, :3]  # Trim C to be 3x3 for compatibility with A
if A.shape[1] == C_trimmed.shape[0]:
    A_x_C = np.dot(A, C_trimmed)
    print("\nMatrix multiplication A * C:")
    print(A_x_C)
else:
    print("\nMatrix multiplication A * C is not valid. Reshaping C.")


Matrix C:
[[ 2  7 11  5]
 [ 9 17 13  4]
 [15 19 14 11]
 [18 15 18 19]]
Rank of matrix C: 4
Submatrix consisting of the first 2 rows and last 2 columns of C:
[[11  5]
 [13  4]]
Frobenius norm of matrix C: 53.76802023508026

Matrix multiplication A * C:
[[ 65  98  79]
 [143 227 193]
 [299 485 421]]


In [5]:
# 5. Data Science Context

# Create a dataset as a 5x5 matrix D
D = np.array([[3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10],
              [1, 3, 5, 7, 9],
              [4, 6, 8, 10, 12],
              [5, 7, 9, 11, 13]])

print("\nDataset D:")
print(D)

# - Standardize D column-wise (mean = 0, variance = 1)
D_standardized = (D - np.mean(D, axis=0)) / np.std(D, axis=0)
print("\nStandardized dataset D (mean = 0, variance = 1):")
print(D_standardized)

# - Compute the covariance matrix of D
cov_D = np.cov(D_standardized, rowvar=False)
print("\nCovariance matrix of D:")
print(cov_D)

# - Perform Principal Component Analysis (PCA)
eigenvalues_cov, eigenvectors_cov = np.linalg.eig(cov_D)
print("\nEigenvalues of covariance matrix:")
print(eigenvalues_cov)
print("Eigenvectors of covariance matrix:")
print(eigenvectors_cov)

# - Reduce D to 2 principal components
D_reduced = D_standardized.dot(eigenvectors_cov[:, :2])
print("\nDataset D reduced to 2 principal components:")
print(D_reduced)


Dataset D:
[[ 3  5  7  9 11]
 [ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 4  6  8 10 12]
 [ 5  7  9 11 13]]

Standardized dataset D (mean = 0, variance = 1):
[[ 0.          0.          0.          0.          0.        ]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [-1.41421356 -1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [ 0.70710678  0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356  1.41421356]]

Covariance matrix of D:
[[1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]
 [1.25 1.25 1.25 1.25 1.25]]

Eigenvalues of covariance matrix:
[ 6.25000000e+00 -3.69778549e-32 -4.19340966e-17  0.00000000e+00
 -2.28523622e-64]
Eigenvectors of covariance matrix:
[[ 4.47213595e-01 -2.01000734e-16 -3.25055279e-01 -4.98525175e-49
   8.98516042e-34]
 [ 4.47213595e-01  8.66025404e-01  8.88074128e-01  5.96701066e-33
  -1.29791556e-17]
 [ 4.47213595e-01 -2.88675135e-01 -1.87672